apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dujbq4lpr-python
  janus-idp.io/tekton: dujbq4lpr-python
  backstage.io/kubernetes-id: dujbq4lpr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dujbq4lpr-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
